project_id = "iobdhtaofnyznjlwvati"

[functions.match-competitor-color]
verify_jwt = false

[functions.visualize-room]
verify_jwt = false

[functions.segment-room-surface]
verify_jwt = false

[functions.match-color-photo]
nverify_jwt = false
