[build]
  command = "npx tsr generate && vite build && esbuild server.ts --bundle --platform=node --format=cjs --packages=external --sourcemap --outfile=dist/server.cjs"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
