/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProHubRouteImport } from './routes/pro-hub'
import { Route as MarineRouteImport } from './routes/marine'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FamilyIslandsRouteImport } from './routes/family-islands'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContractorProgramRouteImport } from './routes/contractor-program'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as BundlesRouteImport } from './routes/bundles'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProHubIndexRouteImport } from './routes/pro-hub.index'
import { Route as ProHubSavedRouteImport } from './routes/pro-hub.saved'
import { Route as ProHubReorderRouteImport } from './routes/pro-hub.reorder'
import { Route as ProHubProjectsRouteImport } from './routes/pro-hub.projects'
import { Route as ProHubCreditRouteImport } from './routes/pro-hub.credit'
import { Route as ProHubColorMatcherRouteImport } from './routes/pro-hub.color-matcher'
import { Route as ProHubAiHubRouteImport } from './routes/pro-hub.ai-hub'
import { Route as ProHubAiDesignToolsRouteImport } from './routes/pro-hub.ai-design-tools'
import { Route as ProHubAiAdvisorRouteImport } from './routes/pro-hub.ai-advisor'
import { Route as OrderConfirmationOrderIdRouteImport } from './routes/order-confirmation.$orderId'
import { Route as DashboardProductsRouteImport } from './routes/dashboard.products'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard.orders'
import { Route as DashboardFollowupsRouteImport } from './routes/dashboard.followups'
import { Route as DashboardColorsRouteImport } from './routes/dashboard.colors'
import { Route as DashboardClientsRouteImport } from './routes/dashboard.clients'
import { Route as DashboardBundlesRouteImport } from './routes/dashboard.bundles'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminColorMatcherRouteImport } from './routes/admin.color-matcher'
import { Route as AdminChangePasswordRouteImport } from './routes/admin.change-password'
import { Route as ProHubProjectsProjectIdRouteImport } from './routes/pro-hub.projects.$projectId'
import { Route as DashboardProductsImportRouteImport } from './routes/dashboard.products.import'
import { Route as DashboardOrdersNewRouteImport } from './routes/dashboard.orders.new'
import { Route as DashboardOrdersOrderIdRouteImport } from './routes/dashboard.orders.$orderId'
import { Route as DashboardColorsImportRouteImport } from './routes/dashboard.colors.import'

const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProHubRoute = ProHubRouteImport.update({
  id: '/pro-hub',
  path: '/pro-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const MarineRoute = MarineRouteImport.update({
  id: '/marine',
  path: '/marine',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyIslandsRoute = FamilyIslandsRouteImport.update({
  id: '/family-islands',
  path: '/family-islands',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorProgramRoute = ContractorProgramRouteImport.update({
  id: '/contractor-program',
  path: '/contractor-program',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const BundlesRoute = BundlesRouteImport.update({
  id: '/bundles',
  path: '/bundles',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProHubIndexRoute = ProHubIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProHubRoute,
} as any)
const ProHubSavedRoute = ProHubSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => ProHubRoute,
} as any)
const ProHubReorderRoute = ProHubReorderRouteImport.update({
  id: '/reorder',
  path: '/reorder',
  getParentRoute: () => ProHubRoute,
} as any)
const ProHubProjectsRoute = ProHubProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => ProHubRoute,
} as any)
const ProHubCreditRoute = ProHubCreditRouteImport.update({
  id: '/credit',
  path: '/credit',
  getParentRoute: () => ProHubRoute,
} as any)
const ProHubColorMatcherRoute = ProHubColorMatcherRouteImport.update({
  id: '/color-matcher',
  path: '/color-matcher',
  getParentRoute: () => ProHubRoute,
} as any)
const ProHubAiHubRoute = ProHubAiHubRouteImport.update({
  id: '/ai-hub',
  path: '/ai-hub',
  getParentRoute: () => ProHubRoute,
} as any)
const ProHubAiDesignToolsRoute = ProHubAiDesignToolsRouteImport.update({
  id: '/ai-design-tools',
  path: '/ai-design-tools',
  getParentRoute: () => ProHubRoute,
} as any)
const ProHubAiAdvisorRoute = ProHubAiAdvisorRouteImport.update({
  id: '/ai-advisor',
  path: '/ai-advisor',
  getParentRoute: () => ProHubRoute,
} as any)
const OrderConfirmationOrderIdRoute =
  OrderConfirmationOrderIdRouteImport.update({
    id: '/order-confirmation/$orderId',
    path: '/order-confirmation/$orderId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardProductsRoute = DashboardProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFollowupsRoute = DashboardFollowupsRouteImport.update({
  id: '/followups',
  path: '/followups',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardColorsRoute = DashboardColorsRouteImport.update({
  id: '/colors',
  path: '/colors',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientsRoute = DashboardClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBundlesRoute = DashboardBundlesRouteImport.update({
  id: '/bundles',
  path: '/bundles',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminColorMatcherRoute = AdminColorMatcherRouteImport.update({
  id: '/admin/color-matcher',
  path: '/admin/color-matcher',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChangePasswordRoute = AdminChangePasswordRouteImport.update({
  id: '/admin/change-password',
  path: '/admin/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProHubProjectsProjectIdRoute = ProHubProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProHubProjectsRoute,
} as any)
const DashboardProductsImportRoute = DashboardProductsImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => DashboardProductsRoute,
} as any)
const DashboardOrdersNewRoute = DashboardOrdersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardOrdersRoute,
} as any)
const DashboardOrdersOrderIdRoute = DashboardOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => DashboardOrdersRoute,
} as any)
const DashboardColorsImportRoute = DashboardColorsImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => DashboardColorsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bundles': typeof BundlesRoute
  '/calculator': typeof CalculatorRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/contractor-program': typeof ContractorProgramRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/family-islands': typeof FamilyIslandsRoute
  '/login': typeof LoginRoute
  '/marine': typeof MarineRoute
  '/pro-hub': typeof ProHubRouteWithChildren
  '/products': typeof ProductsRoute
  '/admin/change-password': typeof AdminChangePasswordRoute
  '/admin/color-matcher': typeof AdminColorMatcherRoute
  '/admin/login': typeof AdminLoginRoute
  '/dashboard/bundles': typeof DashboardBundlesRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/colors': typeof DashboardColorsRouteWithChildren
  '/dashboard/followups': typeof DashboardFollowupsRoute
  '/dashboard/orders': typeof DashboardOrdersRouteWithChildren
  '/dashboard/products': typeof DashboardProductsRouteWithChildren
  '/order-confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/pro-hub/ai-advisor': typeof ProHubAiAdvisorRoute
  '/pro-hub/ai-design-tools': typeof ProHubAiDesignToolsRoute
  '/pro-hub/ai-hub': typeof ProHubAiHubRoute
  '/pro-hub/color-matcher': typeof ProHubColorMatcherRoute
  '/pro-hub/credit': typeof ProHubCreditRoute
  '/pro-hub/projects': typeof ProHubProjectsRouteWithChildren
  '/pro-hub/reorder': typeof ProHubReorderRoute
  '/pro-hub/saved': typeof ProHubSavedRoute
  '/pro-hub/': typeof ProHubIndexRoute
  '/dashboard/colors/import': typeof DashboardColorsImportRoute
  '/dashboard/orders/$orderId': typeof DashboardOrdersOrderIdRoute
  '/dashboard/orders/new': typeof DashboardOrdersNewRoute
  '/dashboard/products/import': typeof DashboardProductsImportRoute
  '/pro-hub/projects/$projectId': typeof ProHubProjectsProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bundles': typeof BundlesRoute
  '/calculator': typeof CalculatorRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/contractor-program': typeof ContractorProgramRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/family-islands': typeof FamilyIslandsRoute
  '/login': typeof LoginRoute
  '/marine': typeof MarineRoute
  '/products': typeof ProductsRoute
  '/admin/change-password': typeof AdminChangePasswordRoute
  '/admin/color-matcher': typeof AdminColorMatcherRoute
  '/admin/login': typeof AdminLoginRoute
  '/dashboard/bundles': typeof DashboardBundlesRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/colors': typeof DashboardColorsRouteWithChildren
  '/dashboard/followups': typeof DashboardFollowupsRoute
  '/dashboard/orders': typeof DashboardOrdersRouteWithChildren
  '/dashboard/products': typeof DashboardProductsRouteWithChildren
  '/order-confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/pro-hub/ai-advisor': typeof ProHubAiAdvisorRoute
  '/pro-hub/ai-design-tools': typeof ProHubAiDesignToolsRoute
  '/pro-hub/ai-hub': typeof ProHubAiHubRoute
  '/pro-hub/color-matcher': typeof ProHubColorMatcherRoute
  '/pro-hub/credit': typeof ProHubCreditRoute
  '/pro-hub/projects': typeof ProHubProjectsRouteWithChildren
  '/pro-hub/reorder': typeof ProHubReorderRoute
  '/pro-hub/saved': typeof ProHubSavedRoute
  '/pro-hub': typeof ProHubIndexRoute
  '/dashboard/colors/import': typeof DashboardColorsImportRoute
  '/dashboard/orders/$orderId': typeof DashboardOrdersOrderIdRoute
  '/dashboard/orders/new': typeof DashboardOrdersNewRoute
  '/dashboard/products/import': typeof DashboardProductsImportRoute
  '/pro-hub/projects/$projectId': typeof ProHubProjectsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bundles': typeof BundlesRoute
  '/calculator': typeof CalculatorRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/contractor-program': typeof ContractorProgramRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/family-islands': typeof FamilyIslandsRoute
  '/login': typeof LoginRoute
  '/marine': typeof MarineRoute
  '/pro-hub': typeof ProHubRouteWithChildren
  '/products': typeof ProductsRoute
  '/admin/change-password': typeof AdminChangePasswordRoute
  '/admin/color-matcher': typeof AdminColorMatcherRoute
  '/admin/login': typeof AdminLoginRoute
  '/dashboard/bundles': typeof DashboardBundlesRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/colors': typeof DashboardColorsRouteWithChildren
  '/dashboard/followups': typeof DashboardFollowupsRoute
  '/dashboard/orders': typeof DashboardOrdersRouteWithChildren
  '/dashboard/products': typeof DashboardProductsRouteWithChildren
  '/order-confirmation/$orderId': typeof OrderConfirmationOrderIdRoute
  '/pro-hub/ai-advisor': typeof ProHubAiAdvisorRoute
  '/pro-hub/ai-design-tools': typeof ProHubAiDesignToolsRoute
  '/pro-hub/ai-hub': typeof ProHubAiHubRoute
  '/pro-hub/color-matcher': typeof ProHubColorMatcherRoute
  '/pro-hub/credit': typeof ProHubCreditRoute
  '/pro-hub/projects': typeof ProHubProjectsRouteWithChildren
  '/pro-hub/reorder': typeof ProHubReorderRoute
  '/pro-hub/saved': typeof ProHubSavedRoute
  '/pro-hub/': typeof ProHubIndexRoute
  '/dashboard/colors/import': typeof DashboardColorsImportRoute
  '/dashboard/orders/$orderId': typeof DashboardOrdersOrderIdRoute
  '/dashboard/orders/new': typeof DashboardOrdersNewRoute
  '/dashboard/products/import': typeof DashboardProductsImportRoute
  '/pro-hub/projects/$projectId': typeof ProHubProjectsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bundles'
    | '/calculator'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/contractor-program'
    | '/dashboard'
    | '/family-islands'
    | '/login'
    | '/marine'
    | '/pro-hub'
    | '/products'
    | '/admin/change-password'
    | '/admin/color-matcher'
    | '/admin/login'
    | '/dashboard/bundles'
    | '/dashboard/clients'
    | '/dashboard/colors'
    | '/dashboard/followups'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/order-confirmation/$orderId'
    | '/pro-hub/ai-advisor'
    | '/pro-hub/ai-design-tools'
    | '/pro-hub/ai-hub'
    | '/pro-hub/color-matcher'
    | '/pro-hub/credit'
    | '/pro-hub/projects'
    | '/pro-hub/reorder'
    | '/pro-hub/saved'
    | '/pro-hub/'
    | '/dashboard/colors/import'
    | '/dashboard/orders/$orderId'
    | '/dashboard/orders/new'
    | '/dashboard/products/import'
    | '/pro-hub/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bundles'
    | '/calculator'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/contractor-program'
    | '/dashboard'
    | '/family-islands'
    | '/login'
    | '/marine'
    | '/products'
    | '/admin/change-password'
    | '/admin/color-matcher'
    | '/admin/login'
    | '/dashboard/bundles'
    | '/dashboard/clients'
    | '/dashboard/colors'
    | '/dashboard/followups'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/order-confirmation/$orderId'
    | '/pro-hub/ai-advisor'
    | '/pro-hub/ai-design-tools'
    | '/pro-hub/ai-hub'
    | '/pro-hub/color-matcher'
    | '/pro-hub/credit'
    | '/pro-hub/projects'
    | '/pro-hub/reorder'
    | '/pro-hub/saved'
    | '/pro-hub'
    | '/dashboard/colors/import'
    | '/dashboard/orders/$orderId'
    | '/dashboard/orders/new'
    | '/dashboard/products/import'
    | '/pro-hub/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bundles'
    | '/calculator'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/contractor-program'
    | '/dashboard'
    | '/family-islands'
    | '/login'
    | '/marine'
    | '/pro-hub'
    | '/products'
    | '/admin/change-password'
    | '/admin/color-matcher'
    | '/admin/login'
    | '/dashboard/bundles'
    | '/dashboard/clients'
    | '/dashboard/colors'
    | '/dashboard/followups'
    | '/dashboard/orders'
    | '/dashboard/products'
    | '/order-confirmation/$orderId'
    | '/pro-hub/ai-advisor'
    | '/pro-hub/ai-design-tools'
    | '/pro-hub/ai-hub'
    | '/pro-hub/color-matcher'
    | '/pro-hub/credit'
    | '/pro-hub/projects'
    | '/pro-hub/reorder'
    | '/pro-hub/saved'
    | '/pro-hub/'
    | '/dashboard/colors/import'
    | '/dashboard/orders/$orderId'
    | '/dashboard/orders/new'
    | '/dashboard/products/import'
    | '/pro-hub/projects/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BundlesRoute: typeof BundlesRoute
  CalculatorRoute: typeof CalculatorRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  ContractorProgramRoute: typeof ContractorProgramRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FamilyIslandsRoute: typeof FamilyIslandsRoute
  LoginRoute: typeof LoginRoute
  MarineRoute: typeof MarineRoute
  ProHubRoute: typeof ProHubRouteWithChildren
  ProductsRoute: typeof ProductsRoute
  AdminChangePasswordRoute: typeof AdminChangePasswordRoute
  AdminColorMatcherRoute: typeof AdminColorMatcherRoute
  AdminLoginRoute: typeof AdminLoginRoute
  OrderConfirmationOrderIdRoute: typeof OrderConfirmationOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro-hub': {
      id: '/pro-hub'
      path: '/pro-hub'
      fullPath: '/pro-hub'
      preLoaderRoute: typeof ProHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marine': {
      id: '/marine'
      path: '/marine'
      fullPath: '/marine'
      preLoaderRoute: typeof MarineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family-islands': {
      id: '/family-islands'
      path: '/family-islands'
      fullPath: '/family-islands'
      preLoaderRoute: typeof FamilyIslandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractor-program': {
      id: '/contractor-program'
      path: '/contractor-program'
      fullPath: '/contractor-program'
      preLoaderRoute: typeof ContractorProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bundles': {
      id: '/bundles'
      path: '/bundles'
      fullPath: '/bundles'
      preLoaderRoute: typeof BundlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro-hub/': {
      id: '/pro-hub/'
      path: '/'
      fullPath: '/pro-hub/'
      preLoaderRoute: typeof ProHubIndexRouteImport
      parentRoute: typeof ProHubRoute
    }
    '/pro-hub/saved': {
      id: '/pro-hub/saved'
      path: '/saved'
      fullPath: '/pro-hub/saved'
      preLoaderRoute: typeof ProHubSavedRouteImport
      parentRoute: typeof ProHubRoute
    }
    '/pro-hub/reorder': {
      id: '/pro-hub/reorder'
      path: '/reorder'
      fullPath: '/pro-hub/reorder'
      preLoaderRoute: typeof ProHubReorderRouteImport
      parentRoute: typeof ProHubRoute
    }
    '/pro-hub/projects': {
      id: '/pro-hub/projects'
      path: '/projects'
      fullPath: '/pro-hub/projects'
      preLoaderRoute: typeof ProHubProjectsRouteImport
      parentRoute: typeof ProHubRoute
    }
    '/pro-hub/credit': {
      id: '/pro-hub/credit'
      path: '/credit'
      fullPath: '/pro-hub/credit'
      preLoaderRoute: typeof ProHubCreditRouteImport
      parentRoute: typeof ProHubRoute
    }
    '/pro-hub/color-matcher': {
      id: '/pro-hub/color-matcher'
      path: '/color-matcher'
      fullPath: '/pro-hub/color-matcher'
      preLoaderRoute: typeof ProHubColorMatcherRouteImport
      parentRoute: typeof ProHubRoute
    }
    '/pro-hub/ai-hub': {
      id: '/pro-hub/ai-hub'
      path: '/ai-hub'
      fullPath: '/pro-hub/ai-hub'
      preLoaderRoute: typeof ProHubAiHubRouteImport
      parentRoute: typeof ProHubRoute
    }
    '/pro-hub/ai-design-tools': {
      id: '/pro-hub/ai-design-tools'
      path: '/ai-design-tools'
      fullPath: '/pro-hub/ai-design-tools'
      preLoaderRoute: typeof ProHubAiDesignToolsRouteImport
      parentRoute: typeof ProHubRoute
    }
    '/pro-hub/ai-advisor': {
      id: '/pro-hub/ai-advisor'
      path: '/ai-advisor'
      fullPath: '/pro-hub/ai-advisor'
      preLoaderRoute: typeof ProHubAiAdvisorRouteImport
      parentRoute: typeof ProHubRoute
    }
    '/order-confirmation/$orderId': {
      id: '/order-confirmation/$orderId'
      path: '/order-confirmation/$orderId'
      fullPath: '/order-confirmation/$orderId'
      preLoaderRoute: typeof OrderConfirmationOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/products': {
      id: '/dashboard/products'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof DashboardProductsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/followups': {
      id: '/dashboard/followups'
      path: '/followups'
      fullPath: '/dashboard/followups'
      preLoaderRoute: typeof DashboardFollowupsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/colors': {
      id: '/dashboard/colors'
      path: '/colors'
      fullPath: '/dashboard/colors'
      preLoaderRoute: typeof DashboardColorsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clients': {
      id: '/dashboard/clients'
      path: '/clients'
      fullPath: '/dashboard/clients'
      preLoaderRoute: typeof DashboardClientsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bundles': {
      id: '/dashboard/bundles'
      path: '/bundles'
      fullPath: '/dashboard/bundles'
      preLoaderRoute: typeof DashboardBundlesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/color-matcher': {
      id: '/admin/color-matcher'
      path: '/admin/color-matcher'
      fullPath: '/admin/color-matcher'
      preLoaderRoute: typeof AdminColorMatcherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/change-password': {
      id: '/admin/change-password'
      path: '/admin/change-password'
      fullPath: '/admin/change-password'
      preLoaderRoute: typeof AdminChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro-hub/projects/$projectId': {
      id: '/pro-hub/projects/$projectId'
      path: '/$projectId'
      fullPath: '/pro-hub/projects/$projectId'
      preLoaderRoute: typeof ProHubProjectsProjectIdRouteImport
      parentRoute: typeof ProHubProjectsRoute
    }
    '/dashboard/products/import': {
      id: '/dashboard/products/import'
      path: '/import'
      fullPath: '/dashboard/products/import'
      preLoaderRoute: typeof DashboardProductsImportRouteImport
      parentRoute: typeof DashboardProductsRoute
    }
    '/dashboard/orders/new': {
      id: '/dashboard/orders/new'
      path: '/new'
      fullPath: '/dashboard/orders/new'
      preLoaderRoute: typeof DashboardOrdersNewRouteImport
      parentRoute: typeof DashboardOrdersRoute
    }
    '/dashboard/orders/$orderId': {
      id: '/dashboard/orders/$orderId'
      path: '/$orderId'
      fullPath: '/dashboard/orders/$orderId'
      preLoaderRoute: typeof DashboardOrdersOrderIdRouteImport
      parentRoute: typeof DashboardOrdersRoute
    }
    '/dashboard/colors/import': {
      id: '/dashboard/colors/import'
      path: '/import'
      fullPath: '/dashboard/colors/import'
      preLoaderRoute: typeof DashboardColorsImportRouteImport
      parentRoute: typeof DashboardColorsRoute
    }
  }
}

interface DashboardColorsRouteChildren {
  DashboardColorsImportRoute: typeof DashboardColorsImportRoute
}

const DashboardColorsRouteChildren: DashboardColorsRouteChildren = {
  DashboardColorsImportRoute: DashboardColorsImportRoute,
}

const DashboardColorsRouteWithChildren = DashboardColorsRoute._addFileChildren(
  DashboardColorsRouteChildren,
)

interface DashboardOrdersRouteChildren {
  DashboardOrdersOrderIdRoute: typeof DashboardOrdersOrderIdRoute
  DashboardOrdersNewRoute: typeof DashboardOrdersNewRoute
}

const DashboardOrdersRouteChildren: DashboardOrdersRouteChildren = {
  DashboardOrdersOrderIdRoute: DashboardOrdersOrderIdRoute,
  DashboardOrdersNewRoute: DashboardOrdersNewRoute,
}

const DashboardOrdersRouteWithChildren = DashboardOrdersRoute._addFileChildren(
  DashboardOrdersRouteChildren,
)

interface DashboardProductsRouteChildren {
  DashboardProductsImportRoute: typeof DashboardProductsImportRoute
}

const DashboardProductsRouteChildren: DashboardProductsRouteChildren = {
  DashboardProductsImportRoute: DashboardProductsImportRoute,
}

const DashboardProductsRouteWithChildren =
  DashboardProductsRoute._addFileChildren(DashboardProductsRouteChildren)

interface DashboardRouteChildren {
  DashboardBundlesRoute: typeof DashboardBundlesRoute
  DashboardClientsRoute: typeof DashboardClientsRoute
  DashboardColorsRoute: typeof DashboardColorsRouteWithChildren
  DashboardFollowupsRoute: typeof DashboardFollowupsRoute
  DashboardOrdersRoute: typeof DashboardOrdersRouteWithChildren
  DashboardProductsRoute: typeof DashboardProductsRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBundlesRoute: DashboardBundlesRoute,
  DashboardClientsRoute: DashboardClientsRoute,
  DashboardColorsRoute: DashboardColorsRouteWithChildren,
  DashboardFollowupsRoute: DashboardFollowupsRoute,
  DashboardOrdersRoute: DashboardOrdersRouteWithChildren,
  DashboardProductsRoute: DashboardProductsRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ProHubProjectsRouteChildren {
  ProHubProjectsProjectIdRoute: typeof ProHubProjectsProjectIdRoute
}

const ProHubProjectsRouteChildren: ProHubProjectsRouteChildren = {
  ProHubProjectsProjectIdRoute: ProHubProjectsProjectIdRoute,
}

const ProHubProjectsRouteWithChildren = ProHubProjectsRoute._addFileChildren(
  ProHubProjectsRouteChildren,
)

interface ProHubRouteChildren {
  ProHubAiAdvisorRoute: typeof ProHubAiAdvisorRoute
  ProHubAiDesignToolsRoute: typeof ProHubAiDesignToolsRoute
  ProHubAiHubRoute: typeof ProHubAiHubRoute
  ProHubColorMatcherRoute: typeof ProHubColorMatcherRoute
  ProHubCreditRoute: typeof ProHubCreditRoute
  ProHubProjectsRoute: typeof ProHubProjectsRouteWithChildren
  ProHubReorderRoute: typeof ProHubReorderRoute
  ProHubSavedRoute: typeof ProHubSavedRoute
  ProHubIndexRoute: typeof ProHubIndexRoute
}

const ProHubRouteChildren: ProHubRouteChildren = {
  ProHubAiAdvisorRoute: ProHubAiAdvisorRoute,
  ProHubAiDesignToolsRoute: ProHubAiDesignToolsRoute,
  ProHubAiHubRoute: ProHubAiHubRoute,
  ProHubColorMatcherRoute: ProHubColorMatcherRoute,
  ProHubCreditRoute: ProHubCreditRoute,
  ProHubProjectsRoute: ProHubProjectsRouteWithChildren,
  ProHubReorderRoute: ProHubReorderRoute,
  ProHubSavedRoute: ProHubSavedRoute,
  ProHubIndexRoute: ProHubIndexRoute,
}

const ProHubRouteWithChildren =
  ProHubRoute._addFileChildren(ProHubRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BundlesRoute: BundlesRoute,
  CalculatorRoute: CalculatorRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  ContractorProgramRoute: ContractorProgramRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FamilyIslandsRoute: FamilyIslandsRoute,
  LoginRoute: LoginRoute,
  MarineRoute: MarineRoute,
  ProHubRoute: ProHubRouteWithChildren,
  ProductsRoute: ProductsRoute,
  AdminChangePasswordRoute: AdminChangePasswordRoute,
  AdminColorMatcherRoute: AdminColorMatcherRoute,
  AdminLoginRoute: AdminLoginRoute,
  OrderConfirmationOrderIdRoute: OrderConfirmationOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
